<!DOCTYPE html>
<html lang="es">

<head>
  <meta charset="utf-8">
  <title>Kross | Catálogo de Productos</title>

  <!-- Meta responsive -->
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
  
  <!-- Meta theme -->
  <meta name="theme-name" content="kross-bulma" />
  
  <!-- Plugins necesarios -->
  <link rel="stylesheet" href="plugins/bulma/bulma.min.css">
  <link rel="stylesheet" href="plugins/slick/slick.css">
  <link rel="stylesheet" href="plugins/themify-icons/themify-icons.css">

  <!-- Estilo principal -->
  <link href="css/style.css" rel="stylesheet">
  
  <!-- Favicon -->
  <link rel="shortcut icon" href="images/favicon.ico" type="image/x-icon">
  <link rel="icon" href="images/favicon.ico" type="image/x-icon">
</head>

<body>

<header>
  <nav class="navbar is-dark is-fixed-top" role="navigation" aria-label="main navigation">
    <div class="navbar-brand">
      <a class="navbar-item" href="index.html">
        <img src="images/ShopPoom_logo_white.png" width="190" height="60">
      </a>
  
      <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navigation">
        <span aria-hidden="true"></span>
        <span aria-hidden="true"></span>
        <span aria-hidden="true"></span>
      </a>
    </div>
  
    <div id="navigation" class="navbar-menu">
      <div class="navbar-end">
        <a href="index.html" class="navbar-item">Home</a>
       
        <a href="Iniciar_sesion.php" class="navbar-item">Admin</a>
      </div>
    </div>
  </nav>
</header>

<!-- Hero Area -->
<section class="hero-area has-background-primary" id="parallax">
  <div class="container">
    <div class="columns">
      <div class="column is-11-desktop is-offset-1-desktop">
        <h1 class="has-text-white font-tertiary">Catálogo de CAMISETAS</h1>
      </div>
    </div>
  </div>
  <div class="layer-bg is-full">
    <!-- Iconos sociales -->
    <div class="list list-hero-social">
      <a class="list-item has-text-white" href="#"><i class="ti-facebook"></i></a>
      <a class="list-item has-text-white" href="#"><i class="ti-instagram"></i></a>
      <a class="list-item has-text-white" href="#"><i class="ti-dribbble"></i></a>
      <a class="list-item has-text-white" href="#"><i class="ti-twitter"></i></a>
    </div>
  </div>
</section>
<!-- /Hero Area -->

<!-- Sección de Productos -->
<section class="section">
  <div class="container">
    <div class="columns is-multiline">

      <!-- Producto 1 -->
      <div class="column is-3-desktop is-6-tablet">
        <div class="card shadow has-text-centered">
          <div class="card-image">
            <figure class="image is-4by3">
              <img src="PRENDAS/PRENDA DIOR.avif" alt="Producto 1">
            </figure>
          </div>
          <div class="card-content has-background-white">
            <h4 class="title is-4">Camiseta Dior</h4>
            <p class="subtitle is-6">Camisa Negra Dior.</p>
            <p class="price is-size-5 has-text-primary">Precio: $60.99</p>
            
          </div>
        </div>
      </div>

      <!-- Producto 2 -->
      <div class="column is-3-desktop is-6-tablet">
        <div class="card shadow has-text-centered">
          <div class="card-image">
            <figure class="image is-4by3">
              <img src="PRENDAS/PRENDA GUCCI.avif" alt="Producto 2">
            </figure>
          </div>
          <div class="card-content has-background-white">
            <h4 class="title is-4">Camiseta Gucci</h4>
            <p class="subtitle is-6">Camisa negra.</p>
            <p class="price is-size-5 has-text-primary">Precio: $99.99</p>
            
          </div>
        </div>
      </div>

      <!-- Producto 3 -->
      <div class="column is-3-desktop is-6-tablet">
        <div class="card shadow has-text-centered">
          <div class="card-image">
            <figure class="image is-4by3">
              <img src="PRENDAS/PRENDA SUPREME.avif" alt="Producto 3">
            </figure>
          </div>
          <div class="card-content has-background-white">
            <h4 class="title is-4">Camiseta Supreme</h4>
            <p class="subtitle is-6">Camisa basica negra.</p>
            <p class="price is-size-5 has-text-primary">Precio: $88.99</p>
            
          </div>
        </div>
      </div>

      <!-- Producto 4 -->
      <div class="column is-3-desktop is-6-tablet">
        <div class="card shadow has-text-centered">
          <div class="card-image">
            <figure class="image is-4by3">
              <img src="PRENDAS/CAMISETA NIKE.webp" alt="Producto 4">
            </figure>
          </div>
          <div class="card-content has-background-white">
            <h4 class="title is-4">Camiseta nike</h4>
            <p class="subtitle is-6">Camisa negra basica nike.</p>
            <p class="price is-size-5 has-text-primary">Precio: $30.99</p>
            
          </div>
        </div>
      </div>

      <!-- Producto 5 -->
      <div class="column is-3-desktop is-6-tablet">
        <div class="card shadow has-text-centered">
          <div class="card-image">
            <figure class="image is-4by3">
              <img src="PRENDAS/camiseta supreme.webp" alt="Producto 5">
            </figure>
          </div>
          <div class="card-content has-background-white">
            <h4 class="title is-4">Camiseta blanca Supreme</h4>
            <p class="subtitle is-6">Camisa blanca basica.</p>
            <p class="price is-size-5 has-text-primary">Precio: $67.99</p>
            
          </div>
        </div>
      </div>

    </div>
  </div>
</section>
<!-- /Sección de Productos -->

<!-- Footer -->
<footer class="has-background-dark footer-section" id="footer">
  <div class="section">
    <div class="container">
      <div class="columns">
        <div class="column is-4-tablet">
          <h5 class="has-text-light">Correo</h5>
          <p class="has-text-white paragraph-lg font-secondary">bpoomflores@gmail.com</p>
        </div>
        <div class="column is-4-tablet">
          <h5 class="has-text-light">Teléfono</h5>
          <p class="has-text-white paragraph-lg font-secondary">+52 631 132 9478</p>
        </div>
        <div class="column is-4-tablet">
          <h5 class="has-text-light">Dirección</h5>
          <p class="has-text-white paragraph-lg font-secondary">ACACIAS 8#C, SONORA, MÉXICO</p>
        </div>
      </div>
    </div>
  </div>
  <div class="section is-small has-text-centered has-border-top is-border-dark">
    <p class="has-text-light">ShopPoom ©
      <script>
        var CurrentYear = new Date().getFullYear()
        document.write(CurrentYear)
      </script> papos <a href="themefisher.com">wow</a></p>
  </div>
</footer>
<!-- /Footer -->

<!-- jQuery -->
<script src="plugins/jQuery/jquery.min.js"></script>
<!-- slick slider -->
<script src="plugins/slick/slick.min.js"></script>
<!-- Main Script -->
<script src="js/script.js"></script>

</body>
</html>
